### ISSUE TITLE
emails: Send emails asynchronously.

### ISSUE THREAD

**Issue by digi0ps** [uniqna/uniqna#56]
Right now the *Forgot password* email is being sent spontaneously. This doesn't allow the user to do anything else until the email is sent. So sending emails asynchronously using a distributed task queue like [Celery](http://www.celeryproject.org/).

**Comment by jeremyphilemon** [comment]
Take a look at [sendgrid](https://sendgrid.com/).

**Comment by digi0ps** [comment]
PR #67 fixes this.
