### ISSUE TITLE
Voting not working for posts which are paginated.

### ISSUE THREAD

**Issue by digi0ps** [uniqna/uniqna#58]
The voting doesn't work for elements which get inserted after we click "Load More". I guess this is because the event handler for the voting function doesn't get attached to them as they are loaded after the script is executed. So we may have to attach the handlers once again after each element is loaded. I will work on a fix for this soon!

**Comment by jeremyphilemon** [comment]
Follow up glitch I found. In the user page where a question can get repeated twice, the voting calls work only for the first instance of the question and not for the ones below it. The same glitch is experienced by the flair's tooltip.

I'm guessing this has something to do with repeated ids?

**Comment by digi0ps** [comment]
@jeremyphilemon the follow up glitch is not related to this issue. I will fix it in a separate commit!
