### ISSUE TITLE
(Number of Replies) value should be called dynamically

### ISSUE THREAD

**Issue by jeremyphilemon** [uniqna/uniqna#61]
Currently, the number of replies get its value from the database table. Rather, it would be better if we could just query the number of replies.

**Comment by digi0ps** [comment]
Where are we displaying the number of replies?

**Comment by jeremyphilemon** [comment]
In the post meta, beside the username.

<img width="111" alt="screen shot 2017-05-16 at 10 59 45 am" src="https://cloud.githubusercontent.com/assets/17938322/26091118/d1497b8e-3a26-11e7-8c36-8404e9e0889a.png">

**Comment by digi0ps** [comment]
@jeremyphilemon umm I don't get this... 
You want the replies to update when someone else replies in the same thread?

**Comment by jeremyphilemon** [comment]
No no. We're already doing the updation but through a query call of a field that stores the number of replies explicitly. What I'm asking is to get the number of replies dynamically like how we're fetching the user karma--by not storing the data in a field.
