### ISSUE TITLE
Notification is still attached when the reply/thread is deleted

### ISSUE THREAD

**Issue by jeremyphilemon** [uniqna/uniqna#74]
Notification is still attached when the reply/thread instance is deleted. So when the user clicks the notifications, it returns a 404 error. I think it would be great if we could delete those notification instances when a thread/reply gets deleted. What say @digi0ps ?

**Comment by jeremyphilemon** [comment]
@digi0ps You fixed this right?

**Comment by digi0ps** [comment]
Yes!
