### ISSUE TITLE
Problems with registering

### ISSUE THREAD

**Issue by prastut** [uniqna/uniqna#90]
* On the fly username validation checker should be there. 
* My VIT email is literally prastut.kumar2014@vit.ac.in

<img width="1440" alt="screen shot 2017-07-13 at 12 56 19 am" src="https://user-images.githubusercontent.com/10279686/28136114-2a03797a-6766-11e7-9b1b-82bd6745c585.png">

**Comment by digi0ps** [comment]
- We do have an on the fly username checker (which fires when the username field loses focus after typing). You sure it didn't work? 
- Oops sorry. We thought all students had only *vitstudent.ac.in* as their email domains. :\

**Comment by prastut** [comment]
@digi0ps I can see username checker which tells me that if my username is taken or not. But it doesn't tell me that my username cannot have special characters. 

Also please close this if this issue is fixed. :)

**Comment by digi0ps** [comment]
@prastut Uh sorry yeah we don't do that, we will implement that soon. Will close this after that. :)
