### ISSUE TITLE
Post and Replies need context

### ISSUE THREAD

**Issue by prastut** [uniqna/uniqna#93]
Context Usecase:

Suppose I have answered a question. Now I don't want to scroll and find the question -> I can quickly go to my profile and see my replies -> which I can right now but: 
* I can't see the question so I lose context of what was I even replying to. 
* I can't quick jump to the thread where I have this reply in place. (Something like what FB does when you see your friend commented on a post and then you click on it so FB scrolls automatically to the friend's comment)
* I can't share my answer with somebody -> shareable links is the easiest way to have word of mouth marketing. 

Imagine if I am sharing links like:

> question
Answer by xyz name 

^ xyz name if popular is click bait.

**Comment by prastut** [comment]
I can't label issues right? Label it as enhancement.

**Comment by prastut** [comment]
<img width="263" alt="screen shot 2017-07-18 at 9 06 49 pm 1" src="https://user-images.githubusercontent.com/10279686/28325990-0a98ffd8-6bfd-11e7-8f07-c537fa27aff0.png">

^ Something like this. This is click bait if somebody shares it on any form of social network.

**Comment by jeremyphilemon** [comment]
@prastut Hyperlinking replies would mean adding a permalink option to each answers, yeah? If so, any thoughts on where to place that link glyph and how the UI would be?

**Comment by jeremyphilemon** [comment]
@prastut 
> I can't see the question so I lose context of what was I even replying to.

Thoughts on this?
<img width="742" alt="screen shot 2017-07-20 at 9 14 54 pm" src="https://user-images.githubusercontent.com/17938322/28426382-8d8e8702-6d90-11e7-9649-bf66634f13b6.png">
